// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1u4b9sDFjjSzRddefFWG0WyCooJZ5m6Q',
    appId: '1:632492192911:web:98d5bf9f69154830526cfa',
    messagingSenderId: '632492192911',
    projectId: 'bucketlistwithfirebase-80d44',
    authDomain: 'bucketlistwithfirebase-80d44.firebaseapp.com',
    storageBucket: 'bucketlistwithfirebase-80d44.appspot.com',
    measurementId: 'G-LVVCPDQ4CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoa4_geceGQVmR8UVlE9JGLZi6VjlUxnI',
    appId: '1:632492192911:android:bae8bd579cbf56fc526cfa',
    messagingSenderId: '632492192911',
    projectId: 'bucketlistwithfirebase-80d44',
    storageBucket: 'bucketlistwithfirebase-80d44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqha98H7VxZ2nvZBB5QdhXzdLppgJVbvQ',
    appId: '1:632492192911:ios:67d79b2a4384629b526cfa',
    messagingSenderId: '632492192911',
    projectId: 'bucketlistwithfirebase-80d44',
    storageBucket: 'bucketlistwithfirebase-80d44.appspot.com',
    iosClientId: '632492192911-47nc735fr0d9ql0mr9ri516qocejnak3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bucketListWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqha98H7VxZ2nvZBB5QdhXzdLppgJVbvQ',
    appId: '1:632492192911:ios:d8e9edafde2d63e2526cfa',
    messagingSenderId: '632492192911',
    projectId: 'bucketlistwithfirebase-80d44',
    storageBucket: 'bucketlistwithfirebase-80d44.appspot.com',
    iosClientId: '632492192911-r4gbc5ohanpq6b60m8s9jvjp5p0n918e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bucketListWithFirebase.RunnerTests',
  );
}
